module.exports = [
    {"id":"MA080",
      "name":"高等数学（A）（1）",
      "ename":"Calculus 1",
      "src":"",
      "credit":"6",
      "lesson":"96",
    },
    {"id":"MA081",
      "name":"高等数学（A）（2）",
      "ename":"Calculus 2",
      "src":"",
      "credit":"4",
      "lesson":"68",
    },
    {"id":"MA077",
      "name":"线性代数（B）",
      "ename":"Linear Algebra",
      "src":"",
      "credit":"3",
      "lesson":"48",
    },
    {"id":"MA115",
      "name":"离散数学",
      "ename":"Discrete Mathematics",
      "src":"",
      "credit":"2",
      "lesson":"32",
    },
    {"id":"CS902",
      "name":"程序设计思想与方法",
      "ename":"Thinking and Approach of Programming",
      "src":"",
      "credit":"3",
      "lesson":"48",
    },
    {"id":"PH001",
      "name":"大学物理（A类）（1）",
      "ename":"Physics 1",
      "src":"",
      "credit":"4",
      "lesson":"68",
    },
    {"id":"PH002",
      "name":"大学物理（A类）（2）",
      "ename":"Physics 2",
      "src":"",
      "credit":"4",
      "lesson":"68",
    },
    {"id":"MA119",
      "name":"概率统计",
      "ename":"Probability and Statistics",
      "src":"",
      "credit":"3",
      "lesson":"51",
    },
    {"id":"SE117",
      "name":"程序设计与数据结构",
      "ename":"Programming and Data Structures I",
      "src":"",
      "credit":"5",
      "lesson":"80",
    },
    {"id":"SE101",
      "name":"计算机系统基础（1）",
      "ename":"Introduction to Computer Systems I",
      "src":"",
      "credit":"5",
      "lesson":"80",
    },
    {"id":"SE111",
      "name":"计算机系统基础（2）",
      "ename":"Introduction to Computer Systems II",
      "src":"",
      "credit":"4",
      "lesson":"64",
    },
    {"id":"SE222",
      "name":"算法原理",
      "ename":"Algorithm",
      "src":"",
      "credit":"3",
      "lesson":"48",
    },
    {"id":"EI235",
      "name":"电路系统综合",
      "ename":"Synthesis of Circuits Systems",
      "src":"",
      "credit":"3",
      "lesson":"48",
    },
    {"id":"PI919",
      "name":"西方哲学史",
      "ename":"The History of Western Philosophy",
      "src":"",
      "credit":"3",
      "lesson":"48",
    },
    {"id":"MU901",
      "name":"交响音乐鉴赏",
      "ename":"Symphonic Music Appreciation",
      "src":"",
      "credit":"2",
      "lesson":"32",
    },
    {"id":"MU902",
      "name":"中西乐理及其应用",
      "ename":"Music Theory",
      "src":"",
      "credit":"2",
      "lesson":"32",
    },
    {"id":"BI903",
      "name":"生命科学实验探索",
      "ename":"Experimental Exploration to Life Science",
      "src":"",
      "credit":"2",
      "lesson":"32",
    },

]
